{
  "extends": ["stylelint-config-standard", "stylelint-prettier/recommended"],
  "plugins": ["stylelint-prettier"],
  "rules": {
    "prettier/prettier": true,
    "declaration-property-value-no-unknown": [
      true,
      {
        "ignoreProperties": {
          "box-shadow": ["/rgba/"]
        }
      }
    ]
  }
}
