{
    "extends": ["stylelint-config-standard", "stylelint-prettier/recommended"],
    "plugins": ["stylelint-prettier"],
    "rules":
        {
            "prettier/prettier": true,
            "property-no-unknown": null,
            "selector-class-pattern",
        },
}
